server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    access-secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    refresh-secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    access-expiration: 600000  # 10 min: 10min * 60 sec * 1000 millisecond
    refresh-expiration: 10800000  # 10800000 3 hours: 3hours * 60min * 60sec * 1000 millisecond

